# Configuración Markdownlint para el Proyecto Asistencia
# Basada en GUIA-ESTILO-MARKDOWN.md v1.0.0
# Fecha: 2025-11-07

# Reglas de Encabezados
MD001: true  # Incremento de encabezados de a un nivel (no saltar de H1 a H3)
MD003:       # Estilo de encabezados (ATX - con #)
  style: atx
MD022: true  # Líneas en blanco antes y después de encabezados
MD023: false # Permitir encabezados que no comienzan al inicio de la línea
MD024:       # No permitir encabezados duplicados (excepto si están separados)
  siblings_only: true
MD025: true  # Solo un H1 por documento
MD026:       # Sin puntuación al final de encabezados
  punctuation: ':'

# Reglas de Líneas en Blanco
MD012:       # Múltiples líneas en blanco consecutivas
  maximum: 2
MD031: true  # Líneas en blanco alrededor de code blocks
MD032: true  # Líneas en blanco alrededor de listas
MD047: true  # Archivo debe terminar con línea en blanco

# Reglas de Listas
MD004:       # Estilo de bullets
  style: dash  # Usar guión medio '-'
MD005: true  # Indentación consistente en listas
MD007:       # Indentación de listas
  indent: 2
  start_indented: false
MD030:       # Espacios después de marcadores de lista
  ul_single: 1
  ul_multi: 1

# Reglas de Code Blocks
MD040: true  # Siempre especificar lenguaje en code blocks
MD046:       # Estilo de code blocks
  style: fenced
MD048:       # Estilo de code fence
  style: backtick

# Reglas de Separadores
MD035:       # Estilo de separadores horizontales
  style: '---'

# Reglas de Enlaces
MD034: false # Permitir URLs sin formato de enlace (para archivos técnicos)
MD051: true  # Validar fragmentos de enlaces

# Reglas de Espacios
MD009:       # Sin espacios al final de línea
  br_spaces: 0
  list_item_empty_lines: false
MD010: false # Permitir tabs (para code blocks)
MD013:       # Longitud de línea
  line_length: 120
  heading_line_length: 80
  code_block_line_length: 120
  tables: false
  headings: true
  strict: false

# Reglas de Énfasis
MD036: false # Permitir énfasis como encabezados (para labels como "Nota:")
MD037: true  # Sin espacios dentro de énfasis
MD049:       # Estilo de énfasis
  style: asterisk
MD050:       # Estilo de strong
  style: asterisk

# Reglas Deshabilitadas
MD033: false # Permitir HTML inline (para casos especiales)
MD041: false # No requerir H1 en primera línea (permitir frontmatter)
